// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    [key: string]: any;
}

// 定义wasm文件类型
declare module '*.wasm' {
    const value: WebAssembly.Module;
    export default value;
}
